@extends('layouts.app')
@section('title','TattooEase | Voorwaarden')
@section('content')
<div class="general-container">
    <div id="term-container">
    <h1>Voorwaarden</h1>
    <p>Deze algemene voorwaarden (&quot;Overeenkomst&quot;) beschrijft de algemene voorwaarden voor uw gebruik van de
        <a target="_blank" rel="nofollow" href="http://tattoo-ease.owendewaele.com">tattoo-ease.owendewaele.com</a> website (&quot;Website&quot; of &quot;Service&quot;) en alle aanverwante producten en diensten (gezamenlijke, &quot;Services&quot;). Deze overeenkomst is juridisch bindend tussen u (&quot;Gebruiker&quot;, &quot;U&quot; of &quot;uw&quot;) en deze website-beheerder &quot;beheerder&quot;, &quot;wij&quot;, &quot;ons&quot; of &quot;onze&quot;). Door toegang te krijgen tot en gebruik te maken van de website en diensten, erkent u dat u de voorwaarden van deze overeenkomst hebt gelezen, begrepen en ermee instemt gebonden te zijn. Als u deze overeenkomst aangaat namens een bedrijf of een andere juridische entiteit, verklaart u dat u bevoegd bent om een ​​dergelijke entiteit aan deze overeenkomst te binden, in welk geval de voorwaarden
        &quot;Gebruiker&quot;, &quot;u&quot; of &quot;uw&quot; verwijst naar een dergelijke entiteit. Als u niet over een dergelijke bevoegdheid beschikt, of als u niet akkoord gaat met de voorwaarden van deze overeenkomst, mag u deze overeenkomst niet accepteren en mag u de website en services niet openen en gebruiken. U erkent dat deze overeenkomst een contract is tussen u en de exploitant, ook al is deze elektronisch en niet fysiek door u ondertekend, en is van toepassing op uw gebruik van de website en services.
    </p>
    <h2>Accounts en lidmaatschap
    </h2>
    <p>U moet minimaal 18 jaar oud zijn om de website en services te gebruiken. Door gebruik te maken van de website en diensten en door akkoord te gaan met deze overeenkomst, garandeert en verklaart u dat u ten minste 18 jaar oud bent. Als u een account aanmaakt op de website, bent u verantwoordelijk voor het handhaven van de veiligheid van uw account en bent u volledig verantwoordelijk voor alle activiteiten die onder het account plaatsvinden en alle andere acties die in verband daarmee worden ondernomen. We kunnen, maar zijn niet verplicht, nieuwe accounts controleren en beoordelen voordat u zich kunt aanmelden en de Services kunt gaan gebruiken. Het verstrekken van valse contactgegevens van welke aard dan ook, kan leiden tot de beëindiging van uw account. U dient ons onmiddellijk op de hoogte te stellen van ongeoorloofd gebruik van uw account of andere inbreuken op de beveiliging. Wij zijn niet aansprakelijk voor enig handelen of nalaten door u, inclusief enige schade van welke aard dan ook die is opgelopen als gevolg van dergelijk handelen of nalaten. We kunnen uw account (of een deel daarvan) opschorten, uitschakelen of verwijderen als we vaststellen dat u enige bepaling van deze overeenkomst heeft geschonden of dat uw gedrag of inhoud de neiging zou hebben om onze reputatie en goodwill te schaden. Als we uw account om de voorgaande redenen verwijderen, kunt u zich niet opnieuw registreren voor onze Services. We kunnen uw e-mailadres en internet-protocoladres blokkeren om verdere registratie te voorkomen.
    </p>
    <h2>Gebruikersinhoud</h2>
    <p>Wij bezitten geen gegevens, informatie of materiaal (gezamenlijk &quot; Inhoud &quot;) die u op de Website indient tijdens het gebruik van de Service. U bent als enige verantwoordelijk voor de nauwkeurigheid, kwaliteit, integriteit, wettigheid, betrouwbaarheid, geschiktheid en intellectuele eigendom of het recht op gebruik van alle ingediende inhoud. We kunnen, maar zijn niet verplicht, de inhoud op de website die door u wordt verzonden of gemaakt met behulp van onze services, controleren en beoordelen. U geeft ons toestemming om de inhoud van uw gebruikersaccount te openen, te kopiëren, te distribueren, op te slaan, te verzenden, opnieuw te formatteren, weer te geven en uit te voeren, uitsluitend voor zover dit nodig is om de Services aan u te leveren. Zonder enige van deze verklaringen of garanties te beperken, hebben we het recht, maar niet de verplichting, om naar eigen goeddunken inhoud te weigeren of te verwijderen die, naar onze redelijke mening, een van onze beleidsregels schendt of op enigerlei wijze schadelijk is. of verwerpelijk. U verleent ons ook de licentie voor het gebruiken, reproduceren, aanpassen, wijzigen, publiceren of distribueren van de inhoud die door u is gemaakt of opgeslagen in uw gebruikersaccount voor commerciële, marketing- of gelijkaardige doeleinden.
    </p>
    <h2>Back-ups</h2>
    <p>Wij zijn niet verantwoordelijk voor de inhoud op de website. In geen geval kunnen wij aansprakelijk worden gesteld voor enig verlies van enige inhoud. Het is uw eigen verantwoordelijkheid om een ​​passende back-up van uw inhoud te maken. Niettegenstaande het voorgaande kunnen we in sommige gevallen en in bepaalde omstandigheden, zonder enige verplichting, mogelijk enkele of al uw gegevens die zijn verwijderd, herstellen vanaf een bepaalde datum en tijd waarop we mogelijk een back-up hebben gemaakt voor onze eigen gegevens. doeleinden. We garanderen niet dat de gegevens die u nodig heeft, beschikbaar zullen zijn.
    </p>
    <h2>Links naar andere bronnen
    </h2>
    <p>Hoewel de website en services kunnen linken naar andere bronnen (zoals websites, mobiele applicaties, enz.), Impliceren we, direct of indirect, geen goedkeuring, associatie, sponsoring, goedkeuring of aansluiting bij een gelinkte bron, tenzij specifiek vermeld hierin. Wij zijn niet verantwoordelijk voor het onderzoeken of evalueren, en we staan ​​niet in voor de aanbiedingen van bedrijven of individuen of de inhoud van hun bronnen. We aanvaarden geen enkele verantwoordelijkheid of aansprakelijkheid voor de acties, producten, diensten en inhoud van andere derden. U dient de juridische verklaringen en andere gebruiksvoorwaarden van alle bronnen die u via een link op de Website en Services opent, zorgvuldig te lezen. Het verwijzen naar andere off-site bronnen is op eigen risico.
    </p>
    <h2>Verboden gebruik
    </h2>
    <p>Naast andere voorwaarden zoals uiteengezet in de Overeenkomst, is het verboden om de Website en Diensten of Inhoud te gebruiken: (a) voor enig onwettig doel; (b) om anderen te vragen om onwettige handelingen uit te voeren of eraan deel te nemen; (c) om internationale, federale, provinciale of nationale voorschriften, regels, wetten of lokale verordeningen te schenden; (d) om inbreuk te maken op onze intellectuele eigendomsrechten of de intellectuele eigendomsrechten van anderen of deze te schenden; (e) om lastig te vallen, te misbruiken, te beledigen, te schaden, te belasteren, te belasteren, te kleineren, te intimideren of te discrimineren op basis van geslacht, seksuele geaardheid, religie, etniciteit, ras, leeftijd, nationale afkomst of handicap; (f) om valse of misleidende informatie te verstrekken; (g) om virussen of enig ander type kwaadaardige code te uploaden of te verzenden die zal of kan worden gebruikt op een manier die de functionaliteit of werking van de Website en Diensten, producten en diensten van derden of het internet beïnvloedt; (h) om te spammen, phishing, pharm, voorwendsel, spider, crawl of scrape; (i) voor enig obsceen of immoreel doel; of (j) om de beveiligingsfuncties van de Website en Services, producten en services van derden of internet te verstoren of te omzeilen. We behouden ons het recht voor om uw gebruik van de website en services te beëindigen wegens het schenden van verboden gebruik.
    </p>
    <h2>Intellectuele eigendomsrechten
    </h2>
    <p>&quot;Intellectuele eigendomsrechten&quot; betekent alle huidige en toekomstige rechten verleend door de wet, gewoonterecht of billijkheid in of met betrekking tot enig auteursrecht en naburige rechten, handelsmerken, ontwerpen, patenten, uitvindingen, goodwill en het recht om te vervolgen wegens overlijden, rechten op uitvindingen, gebruiksrechten , en alle andere intellectuele eigendomsrechten, in elk geval geregistreerd of niet-geregistreerd en inclusief alle toepassingen en rechten om aan te vragen en te worden verleend, rechten om voorrang te krijgen van, dergelijke rechten en alle soortgelijke of gelijkwaardige rechten of vormen van bescherming en alle andere resultaten van intellectuele activiteit die nu of in de toekomst in enig deel van de wereld bestaat of zal bestaan. Deze Overeenkomst draagt ​​geen enkel intellectueel eigendom over dat eigendom is van de Operator of derden, en alle rechten, titels en belangen in en op dergelijke eigendommen blijven (zoals tussen de partijen) uitsluitend bij de Operator. Alle handelsmerken, servicemerken, afbeeldingen en logo's die worden gebruikt in verband met de website en services, zijn handelsmerken of geregistreerde handelsmerken van de exploitant of zijn licentiegevers. Andere handelsmerken, servicemerken, afbeeldingen en logo's die worden gebruikt in verband met de website en services, kunnen handelsmerken zijn van andere derden. Uw gebruik van de website en services verleent u geen recht of licentie om handelsmerken van de exploitant of van derden te reproduceren of anderszins te gebruiken.
    </p>
    <h2>Beperking van aansprakelijkheid
    </h2>
    <p>Voor zover toegestaan ​​door de toepasselijke wetgeving, zullen de Operator, zijn gelieerde ondernemingen, directeuren, functionarissen, werknemers, agenten, leveranciers of licentiegevers in geen geval aansprakelijk zijn jegens enige persoon voor enige indirecte, incidentele, speciale, bestraffende, dekking of gevolgschade ( inclusief, maar niet beperkt tot, schade voor gederfde winst, inkomsten, verkoop, goodwill, gebruik van inhoud, impact op het bedrijf, bedrijfsonderbreking, verlies van verwachte besparingen, verlies van zakelijke kansen) hoe dan ook veroorzaakt, onder enige aansprakelijkheidstheorie, inclusief, maar niet beperkt tot contract, onrechtmatige daad, garantie, schending van wettelijke plicht, nalatigheid of anderszins, zelfs als de aansprakelijke partij is ingelicht over de mogelijkheid van dergelijke schade of dergelijke schade had kunnen voorzien. Voor zover maximaal toegestaan ​​door de toepasselijke wetgeving, zal de totale aansprakelijkheid van de Operator en zijn gelieerde ondernemingen, functionarissen, werknemers, agenten, leveranciers en licentiegevers met betrekking tot de diensten beperkt zijn tot een bedrag groter dan één dollar of bedragen die daadwerkelijk in contanten zijn betaald door u aan de Operator voor de voorafgaande periode van één maand voorafgaand aan de eerste gebeurtenis of gebeurtenis die aanleiding gaf tot een dergelijke aansprakelijkheid. De beperkingen en uitsluitingen zijn ook van toepassing als deze remedie u niet volledig vergoedt voor eventuele verliezen of als het essentiële doel niet bereikt.
    </p>
    <h2>Vrijwaring</h2>
    <p>U stemt ermee in de Operator en zijn gelieerde ondernemingen, directeuren, functionarissen, werknemers, agenten, leveranciers en licentiegevers schadeloos te stellen en te vrijwaren van en tegen alle aansprakelijkheden, verliezen, schade of kosten, met inbegrip van redelijke advocatenhonoraria, gemaakt in verband met of voortvloeiend uit enige aantijgingen, claims, acties, geschillen of eisen van derden tegen een van hen als gevolg van of verband houdend met uw inhoud, uw gebruik van de website en diensten of enig opzettelijk wangedrag van uw kant.
    </p>
    <h2>Scheidbaarheid</h2>
    <p>Alle rechten en beperkingen in deze overeenkomst kunnen worden uitgeoefend en zijn alleen van toepassing en bindend voor zover ze geen toepasselijke wetten schenden en zijn bedoeld om te worden beperkt tot de mate die nodig is, zodat ze deze overeenkomst niet onwettig, ongeldig maken. of niet afdwingbaar. Als een bepaling of een deel van een bepaling van deze Overeenkomst door een bevoegde rechtbank als onwettig, ongeldig of niet-afdwingbaar wordt beschouwd, is het de bedoeling van de partijen dat de overige bepalingen of delen daarvan hun overeenkomst vormen met betrekking tot de onderwerp hiervan, en al dergelijke overige bepalingen of delen daarvan zullen volledig van kracht en van kracht blijven.
    </p>
    <h2>Geschillenbeslechting</h2>
    <p>De totstandkoming, interpretatie en uitvoering van deze overeenkomst en alle geschillen die daaruit voortvloeien, worden beheerst door het materiële en procedurele recht van België, zonder rekening te houden met de regels inzake conflicten of rechtskeuze en, voor zover van toepassing, het Belgische recht. . De exclusieve jurisdictie en locatie voor acties met betrekking tot het onderwerp hiervan zijn de rechtbanken in België, en u onderwerpt zich hierbij aan de persoonlijke jurisdictie van dergelijke rechtbanken. U doet hierbij afstand van elk recht op juryrechtspraak in een procedure die voortvloeit uit of verband houdt met deze Overeenkomst. Het Verdrag van de Verenigde Naties inzake internationale koopovereenkomsten betreffende roerende zaken is niet van toepassing op deze overeenkomst. </p>
    <p>We behouden ons het recht voor om deze overeenkomst of de voorwaarden met betrekking tot de website en services op elk moment te wijzigen, met ingang van het plaatsen van een bijgewerkte versie van deze overeenkomst op de website. Als we dat doen, sturen we u een e-mail om u hiervan op de hoogte te stellen. Voortgezet gebruik van de website en services na dergelijke wijzigingen houdt uw instemming met dergelijke wijzigingen in. 
    </p>
    <h2>Aanvaarding van deze voorwaarden
    </h2>
    <p>U erkent dat u deze overeenkomst heeft gelezen en akkoord gaat met alle voorwaarden en bepalingen. Door de website en services te openen en te gebruiken, gaat u ermee akkoord gebonden te zijn aan deze overeenkomst. Als u niet akkoord gaat met de voorwaarden van deze overeenkomst, bent u niet bevoegd om toegang te krijgen tot of gebruik te maken van de website en services.
    </p>
    <h2>Contacteer ons</h2>
    <p>Als u contact met ons wilt opnemen om meer te weten te komen over deze Overeenkomst of contact met ons wilt opnemen over enige aangelegenheid die ermee verband houdt, kunt u dat doen via het
        <a target="_blank" rel="nofollow" href="{{route('contact')}}">contact formulier</a></p>
    <p>Dit document is voor het laatst bijgewerkt op
        November 16, 2020</p>
    </div>
</div>
@endsection